"""End-to-end extraction pipeline (PLAN.md §4).

The pipeline is a fixed sequence of stages. Rules are pluggable; everything
else is deterministic. Agents do NOT edit this file.
"""

from __future__ import annotations

from typing import List, Optional

from .config import ExtractionConfig
from .filters import (
    dedup_triplets,
    is_complete,
    is_meaningful_argument,
    is_self_reference,
)
from .models import Argument, Candidate, Triplet
from .preprocess import Parser, mask_markdown
from .rule_registry import discover_rules
from .segment import distribute_subjects, segment_into_clauses
from .shape import shape_argument, shape_predicate, shape_subject
from .shape.predicate import detect_negation_and_modality


class Pipeline:
    """Compose preprocess → segment → propose → shape → filter → dedup → emit.

    Construct once per process; ``extract`` is safe to call repeatedly.
    """

    def __init__(self, config: Optional[ExtractionConfig] = None) -> None:
        self.config = config or ExtractionConfig()
        self.parser = Parser(
            model=self.config.spacy_model,
            use_gliner=self.config.use_gliner,
            gliner_model=self.config.gliner_model,
        )
        self._rule_classes = self._select_rules()
        self._rule_instances = [cls() for cls in self._rule_classes]

    # ----- public surface -----

    def extract(self, text: str) -> List[Triplet]:
        masked = mask_markdown(text)
        doc = self.parser.parse(masked)
        all_triplets: List[Triplet] = []
        for sent in doc.sents:
            sent_triplets = self._extract_from_sent(sent)
            all_triplets.extend(sent_triplets)
        return all_triplets

    # ----- internals -----

    def _select_rules(self):
        all_rules = discover_rules()
        if self.config.enabled_rules is None:
            return list(all_rules.values())
        return [cls for name, cls in all_rules.items() if name in self.config.enabled_rules]

    def _extract_from_sent(self, sent) -> List[Triplet]:
        # Segmentation walks the same Doc so token .i indices stay stable;
        # we then restrict to clauses rooted inside this sentence.
        clauses = segment_into_clauses(sent.doc)
        clauses = distribute_subjects(clauses)
        clauses = [c for c in clauses if sent.start <= c.root.i < sent.end]

        candidates: List[Candidate] = []
        for clause in clauses:
            for rule in self._rule_instances:
                try:
                    for cand in rule.apply(clause):
                        candidates.append(cand)
                except Exception:  # pragma: no cover - rule bug
                    # A broken rule must not crash the pipeline. The
                    # optimization loop's gates will reject it.
                    continue

        shaped: List[Triplet] = [self._shape_candidate(c) for c in candidates]
        kept = [t for t in shaped if t is not None]
        kept = [t for t in kept if is_complete(t, self.config.filters)]
        kept = [t for t in kept if not is_self_reference(t, self.config.filters)]
        kept = [t for t in kept if is_meaningful_argument(t, self.config.filters)]
        return dedup_triplets(kept)

    def _shape_candidate(self, cand: Candidate) -> Optional[Triplet]:
        try:
            if cand.subj_minimal_only:
                h = cand.subject_head
                subject_span = h.doc[h.i:h.i + 1]
            elif cand.subj_span_subtree:
                subject_span = _subtree_span(cand.subject_head)
            else:
                subject_span = shape_subject(cand.subject_head, self.config.shape)
            # No-verb construction (appositive, etc.): predicate is synthesized
            # as a literal string; the anchor span is the predicate_head token.
            if cand.synthesized_predicate_text is not None:
                head = cand.predicate_head
                predicate_span = head.doc[head.i:head.i + 1]
                synth_text = cand.synthesized_predicate_text
                # ``prep`` is consumed by the synthesized-predicate path: do
                # NOT pass it down into the Argument's prep field.
                effective_prep_for_arg = None
                negated_from_parse, modality_from_parse = False, None
            else:
                predicate_span = shape_predicate(
                    cand.predicate_head, self.config.shape, explicit_prep=cand.prep
                )
                synth_text = None
                effective_prep_for_arg = cand.prep
                negated_from_parse, modality_from_parse = detect_negation_and_modality(
                    cand.predicate_head
                )
            arg: Optional[Argument]
            if cand.arg_head is None:
                arg = None
            else:
                if cand.arg_minimal_only:
                    h = cand.arg_head
                    arg_span = h.doc[h.i:h.i + 1]
                elif cand.arg_span_subtree:
                    arg_span = _subtree_span(cand.arg_head)
                else:
                    arg_span = shape_argument(cand.arg_head, self.config.shape)
                arg = Argument(
                    span=arg_span, role=cand.role, prep=effective_prep_for_arg
                )
            return Triplet(
                subject=subject_span,
                predicate=predicate_span,
                argument=arg,
                negated=cand.negated or negated_from_parse,
                modality=cand.modality or modality_from_parse,
                source_rule=cand.source_rule,
                confidence=cand.confidence,
                predicate_text=synth_text,
            )
        except Exception:  # pragma: no cover
            return None


def _subtree_span(head):
    """Contiguous span over ``head.subtree``, trimmed of leading/trailing punct.

    spaCy token .subtree yields tokens in arbitrary order; we sort by .i and
    bracket. Used for clausal argument heads (advcl/ccomp/relcl) where the
    natural span is the embedded clause, not a noun-style expansion.
    """
    from .shape.boundaries import trim_break_punct, trim_trailing_punct

    toks = sorted(head.subtree, key=lambda t: t.i)
    start = toks[0].i
    end = toks[-1].i + 1
    span = head.doc[start:end]
    span = trim_break_punct(span)
    span = trim_trailing_punct(span)
    return span


def extract(text: str, config: Optional[ExtractionConfig] = None) -> List[Triplet]:
    """One-shot convenience entry point."""
    return Pipeline(config).extract(text)
